# .github/workflows/daily_parody_video.yml

name: OU Stock Parody Video Generation

on:
  schedule:
    # 매일 저녁 8시 KST (11:00 UTC)에 실행
    - cron: '0 11 * * *' 
  # 수동 실행을 위한 workflow_dispatch 추가
  workflow_dispatch:
  
jobs:
  generate_parody_video:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 코드 체크아웃
        uses: actions/checkout@v4

      - name: ⚡️ Git LFS 설정
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs
          git lfs install

      - name: 🐍 Python 환경 설정
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 🎬 FFmpeg 설치 (동영상 제작용)
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: 🐍 Python 패키지 설치
        run: pip install -r requirements.txt

      - name: 🔐 환경변수 설정
        env:
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
        run: |
          # Claude API 키 설정
          if [ -z "$CLAUDE_API_KEY" ]; then
            echo "❌ CLAUDE_API_KEY가 설정되지 않았습니다!"
            exit 1
          fi
          echo "CLAUDE_API_KEY=$CLAUDE_API_KEY" >> .env

          # Google 서비스 계정 키 설정
          if [ -z "$GOOGLE_SERVICE_ACCOUNT" ]; then
            echo "❌ GOOGLE_SERVICE_ACCOUNT가 설정되지 않았습니다!"
            exit 1
          fi
          echo "$GOOGLE_SERVICE_ACCOUNT" > google_service_account.json

          echo "✅ 환경변수 설정 완료"

      - name: 🎯 주식 패러디 동영상 생성 실행
        run: |
          python step4_ou_stock_parody_final.py

      - name: 📤 생성된 파일 커밋 및 푸시
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Git LFS로 동영상 파일 추적
          git lfs track "parody_video/*.mp4"
          git add .gitattributes
          
          # 생성된 동영상 파일 추가
          git add parody_video/*.mp4
          
          # 변경사항이 있을 경우에만 커밋 및 푸시
          if git diff --staged --quiet; then
            echo "✅ 변경사항이 없습니다. 커밋을 건너뜁니다."
          else
            echo "🚀 변경사항을 커밋하고 푸시합니다."
            git commit -m "🎬 자동 생성: $(date '+%Y-%m-%d') 주식 패러디 동영상"
            git push
          fi
